{% set name = "libertem-dectris" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libertem_dectris-{{ version }}.tar.gz
  sha256: 02b49e72fa46af475ad375e30e844bfe02d8be89ac7eafc7577aa6b37e341648

build:
  skip: true  # [py<37]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - LIBCLANG_PATH=$BUILD_PREFIX/lib  # [not win]
    - LIBCLANG_PATH=%LIBRARY_BIN%  # [win]

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - rust >=1.66
    - clang
    - libclang
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.3.1,<2
    - cython >=0.19
    - numpy >=1.6.1,<2
    - zeromq
    - clang
    - libclang
    - pip
  run:
    - python

test:
  commands:
    - pip check
  imports:
    - libertem_dectris
  requires:
    - pip

about:
  home: https://github.com/LiberTEM/LiberTEM-rs/
  summary: LiberTEM support for DECTRIS detectors
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: |
    Python package for efficiently receiving data
    from DECTRIS detectors with the zeromq interface

extra:
  recipe-maintainers:
    - sk1p
    - uellue
    - matbryan52
